# frozen_string_literal: true

require 'fileutils'

module Lambda
  module MicroVMs
    # Generates Ruby Lambda MicroVM starter projects.
    class Scaffold
      attr_reader :name, :directory

      def initialize(name, directory: name, force: false)
        @name = name
        @directory = directory
        @force = force
      end

      # Create the scaffolded project files.
      #
      # @return [String] target directory
      def create
        ensure_target!
        FileUtils.mkdir_p(directory)
        write('Gemfile', gemfile)
        write('Dockerfile', dockerfile)
        write('app.rb', app_rb)
        write('microvm.yml', microvm_yml)
        write('README.md', readme)
        write('.env.example', env_example)
        directory
      end

      private

      def ensure_target!
        return if @force || !File.exist?(directory) || Dir.empty?(directory)

        raise ConfigurationError, "target directory is not empty: #{directory}"
      end

      def write(path, content)
        File.write(File.join(directory, path), content)
      end

      def gemfile
        <<~GEMFILE
          source "https://rubygems.org"

          gem "aws_lambda_ric"
          gem "json"
        GEMFILE
      end

      def dockerfile
        <<~DOCKERFILE
          FROM ruby:3.4-slim

          ENV LAMBDA_TASK_ROOT=/var/task
          WORKDIR ${LAMBDA_TASK_ROOT}

          RUN apt-get update \\
              && apt-get install -y --no-install-recommends build-essential \\
              && rm -rf /var/lib/apt/lists/*

          COPY Gemfile ${LAMBDA_TASK_ROOT}/Gemfile
          RUN bundle install

          COPY app.rb ${LAMBDA_TASK_ROOT}/app.rb

          ENTRYPOINT ["bundle", "exec", "aws_lambda_ric"]
          CMD ["app.App::Handler.process"]
        DOCKERFILE
      end

      def app_rb
        <<~RUBY
          # frozen_string_literal: true

          require "json"

          module App
            class Handler
              def self.process(event:, context:)
                {
                  ok: true,
                  message: "Hello from #{name}",
                  event: event,
                  request_id: context.respond_to?(:aws_request_id) ? context.aws_request_id : nil
                }
              end
            end
          end
        RUBY
      end

      def microvm_yml
        <<~YAML
          name: #{name}
          region: us-east-1

          # Optional: AWS profile to use for CLI-driven commands.
          # profile: default

          # IAM role used when running the MicroVM.
          role_arn: arn:aws:iam::123456789012:role/lambda-microvm-runtime

          build:
            dockerfile: Dockerfile
            context: .
            artifact: tmp/#{name}-microvm.zip

          deployment:
            bucket: replace-me-lambda-microvm-artifacts
            prefix: lambda-microvms/#{name}

          image:
            name: #{name}
            # arn: arn:aws:lambda:us-east-1:123456789012:microvm-image:#{name}
            create:
              # Keep this hash close to the AWS Lambda MicroVM create image API shape.
              # lambda-microvms deploy injects code_artifact after S3 upload.
              name: #{name}

          runtime:
            after: suspend
            payload:
              source: lambda-microvms
        YAML
      end

      def readme
        <<~README
          # #{name}

          Ruby AWS Lambda MicroVM application scaffold generated by `lambda-microvms`.

          This project uses `aws_lambda_ric` inside the image so the Ruby handler can speak the Lambda Runtime API.

          ## Local setup

          ```bash
          bundle install
          ```

          ## Build / deploy from the parent toolkit

          ```bash
          lambda-microvms doctor
          lambda-microvms package
          lambda-microvms deploy
          lambda-microvms run
          ```

          Edit `microvm.yml` before deploying.
        README
      end

      def env_example
        <<~ENV
          AWS_REGION=us-east-1
          AWS_PROFILE=default
        ENV
      end
    end
  end
end
